server:
  port: 9982
spring:
  application:
    name: lemon-backup
  boot:
    admin:
      client:
        url: "http://localhost:9983"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name} # 注册到consul的服务名称
lemon:
  backup:
    datasource:
      host: localhost
      username: root
      password: 1015
      database: lemon
# 开启健康端口检查
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always