server:
  port: 9982
spring:
  application:
    name: lemon-backup
  boot:
    admin:
      client:
        url: "http://localhost:9983"
lemon:
  backup:
    datasource:
      host: localhost
      username: root
      password: 1015
      database: lemon